version: '2'
services:
  biffin:
    build: .
    ports:
      - "0.0.0.0:8090:8090"
    environment:
      - DB_DSN=host=postgres user=f3b1be969686afb4520ce dbname=biffin sslmode=disable password=839169c0ea5e59146a
    links:
      - postgres

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=f3b1be969686afb4520ce
      - POSTGRES_PASSWORD=839169c0ea5e59146a
      - POSTGRES_DB=biffin
