version: '2'
services:
  biffin:
    build: .
    ports:
      - "0.0.0.0:8090:8090"
    environment:
      - WS_URI=ws://HOST:PORT/longurl
      - PRIVATE_KEY=7c23f7cc6cd849f7731b9741c26c452ac1b0984453e296799d982b06d57757ea
      - DB_DSN=/tmp/db.sqlite
