package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"

	"github.com/go-openapi/swag"
)

// GetMapURL generates an URL for the get map operation
type GetMapURL struct {
	ID *int64

	// avoid unkeyed usage
	_ struct{}
}

// Build a url path and query string
func (o *GetMapURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/map"

	result.Path = _path

	qs := make(url.Values)

	var id string
	if o.ID != nil {
		id = swag.FormatInt64(*o.ID)
	}
	if id != "" {
		qs.Set("id", id)
	}

	result.RawQuery = qs.Encode()

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetMapURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetMapURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetMapURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetMapURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetMapURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetMapURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
