// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// BaseUnit base unit
// swagger:model BaseUnit
type BaseUnit struct {

	// Index
	Index int64 `json:"index,omitempty"`

	// X position
	X int64 `json:"x,omitempty"`

	// Y position
	Y int64 `json:"y,omitempty"`
}

// Validate validates this base unit
func (m *BaseUnit) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BaseUnit) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BaseUnit) UnmarshalBinary(b []byte) error {
	var res BaseUnit
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
