// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// GameUnit game unit
// swagger:model GameUnit
type GameUnit struct {

	// Name of unit
	Name string `json:"name,omitempty"`

	// X position
	X int64 `json:"x,omitempty"`

	// Y position
	Y int64 `json:"y,omitempty"`
}

// Validate validates this game unit
func (m *GameUnit) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GameUnit) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GameUnit) UnmarshalBinary(b []byte) error {
	var res GameUnit
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
