package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// GameUnit game unit
// swagger:model GameUnit
type GameUnit struct {

	// Name of unit
	Name string `json:"name,omitempty"`

	// X position
	X int64 `json:"x,omitempty"`

	// Y position
	Y int64 `json:"y,omitempty"`
}

// Validate validates this game unit
func (m *GameUnit) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
