package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Layer layer
// swagger:model Layer
type Layer struct {

	// Array of GIDs. tilelayer only.
	Data int64 `json:"data,omitempty"`

	// topdown (default) or index. objectgroup only.
	Draworder string `json:"draworder,omitempty"`

	// Row count. Same as map height in Tiled Qt.
	Height int64 `json:"height,omitempty"`

	// Name assigned to this layer
	Name string `json:"name,omitempty"`

	// Array of Object units. objectgroup only.
	Objects interface{} `json:"objects,omitempty"`

	// Value between 0 and 1
	Opacity float64 `json:"opacity,omitempty"`

	// Horizontal layer offset. Always 0 in Tiled Qt.
	PosX int64 `json:"pos_x,omitempty"`

	// Vertical layer offset. Always 0 in Tiled Qt.
	PosY int64 `json:"pos_y,omitempty"`

	// string key-value pairs.
	Properties interface{} `json:"properties,omitempty"`

	// tilelayer, objectgroup, or imagelayer
	Type string `json:"type,omitempty"`

	// Whether layer is shown or hidden in editor
	Visible bool `json:"visible,omitempty"`

	// Column count. Same as map width in Tiled Qt.
	Width int64 `json:"width,omitempty"`
}

// Validate validates this layer
func (m *Layer) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
