package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// MapFile2 map file2
// swagger:model MapFile2
type MapFile2 struct {

	// Height in pixels. Ignored if using a gid.
	Height int64 `json:"height,omitempty"`

	// Units of the game
	Units interface{} `json:"units,omitempty"`

	// Width in pixels. Ignored if using a gid.
	Width int64 `json:"width,omitempty"`
}

// Validate validates this map file2
func (m *MapFile2) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
