// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Terrain terrain
// swagger:model Terrain
type Terrain struct {

	// Name of terrain
	Name string `json:"name,omitempty"`

	// Local ID of tile representing terrain
	Tile int64 `json:"tile,omitempty"`
}

// Validate validates this terrain
func (m *Terrain) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Terrain) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Terrain) UnmarshalBinary(b []byte) error {
	var res Terrain
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
