package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Terrain terrain
// swagger:model Terrain
type Terrain struct {

	// Name of terrain
	Name string `json:"name,omitempty"`

	// Local ID of tile representing terrain
	Tile int64 `json:"tile,omitempty"`
}

// Validate validates this terrain
func (m *Terrain) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
